---
title: "Forecasting: Principles and Practice"
subtitle: "Chapter 11: Advanced Forecasting Methods"
author: "Darshan Patel"
date: "8/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1: 
Use the `tbats()` function to model your retail time series.

(a) Check the residuals and produce forecasts.

(b) Does this completely automated approach work for these data?

(c) Have you saved any degrees of freedom by using Fourier terms rather than seasonal differencing?


### Question 2:
Consider the weekly data on US finished motor gasoline products supplied (millions of barrels per day) (series `gasoline`):

(a) Fit a TBATS model to these data.

(b) Check the residuals and produce forecasts.

(c) Could you model these data using any of the other methods we have considered in this book?


### Question 3: 
Experiment with using `nnetar()` on your retail data and other data we have considered in previous chapters.







#### Source: Hyndman, R.J., & Athanasopoulos, G. (2018) Forecasting: principles and practice, 2nd edition, OTexts: Melbourne, Australia. OTexts.com/fpp2. Accessed on August 1 2019.
